version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3001:3001"
    env_file: 
      - .env  # Loads variables from .env file
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  mongo-data:
